---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Корзина товаров должна быть доступна при смене браузера и компьютера
  - Пользователь должен иметь возможность регистрации на сайте
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность оформить заказ
  - Пользователь должен иметь возможность при оформлении заказа оставить контактные данные
  - Пользователь должен иметь возможность просматривать текущие и прошлые заказы в личном кабинете
